name: Rust Build with Maturin

on: [push, pull_request]

jobs:
  build-linux:
    name: Build Rust Project on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - name: Install Maturin
        run: |
          python -m pip install maturin

      - name: Build with Maturin
        run: |
          maturin build --release --features py --out dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-amd64
          path: dist/*
  
  build-macos-arm:
    name: Build Rust Project on macOS Arm
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - name: Install Maturin
        run: |
          python -m pip install maturin

      - name: Build with Maturin
        run: |
          maturin build --release --features py --out dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-arm
          path: dist/*

  build-linux-arm64:
    name: Build Rust Project on Linux arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - name: Install Maturin
        run: |
          python -m pip install maturin

      - name: Build with Maturin
        run: |
          maturin build --release --features py --out dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-arm
          path: dist/*
